<?php
namespace Cognosys\Exceptions;
use Cognosys\Templates\View,
	Cognosys\Config,
	Cognosys\TextUtil,
	Cognosys\Mail,
	Cognosys\Error,
	\DateTime;

/**
 * An error generated by a developer fault.
 * This error is treated showing the user a message and sending an email
 * to the 'developers' in Config
 * @author Renato S. Martins <smartins.renato@gmail.com>
 */
class ApplicationError extends Error
{
	public function handle($request, $response, $template)
	{
		$now = new DateTime();
		$time = $now->format(DateTime::RFC850);
		$trace = TextUtil::tabify($this->getTraceAsString(), 1);
		$request = $request
			? TextUtil::tabify($request, 1)
			: '(No request information)';
		$response = $response
			? TextUtil::tabify($response, 1)
			: '(No response information)';
		$view = new View($request, $response);
		$view->setDecorator($template);
		
		$this->message = <<<EOT
{$this->message}

* Time: {$time}
* File: {$this->file}
* Line: {$this->line}
* Trace:
	{$trace}

* Request:
	{$request}

* Response:
	{$response}
EOT;
		
		if (Config::get('development')) {
			$this->message = "<pre>{$this->message}</pre>";
			$view->setText($this->message);
		} else {
			Mail::send(
				Config::get('developers'),
				'Application error',
				$this->message,
				Mail::PRIORITY_HIGH
			);
			$view->setText(
				'An email has been sent to the developers to resolve the issue.'
				. ' Thank you.'
			);
		}
		
		$view->render();
		$view->show();
	}
}
