<?php
namespace Cognosys\Exceptions;
use Cognosys\Layout,
	Cognosys\Config,
	Cognosys\TextUtil,
	Cognosys\Mail,
	Cognosys\Error,
	\DateTime;

/**
 * An error generated by a developer fault.
 * This error is treated showing the user a message and sending an email
 * to the 'developers' in Config
 * @author Renato S. Martins <smartins.renato@gmail.com>
 */
class ApplicationError extends Error
{
	public function handle($request, $response)
	{
		$now = new DateTime();
		$time = $now->format(DateTime::RFC850);
		$trace = TextUtil::tabify($this->getTraceAsString(), 2);
		$request = $request
			? TextUtil::tabify($request, 2)
			: '(No request information)';
		$response = $response
			? TextUtil::tabify($response, 2)
			: '(No response information)';
		
		$content = <<<EOT
{$this->message}

	* Time: {$time}
	* File: {$this->file}
	* Line: {$this->line}
	* Trace:
		{$trace}

	* Request:
		{$request}

	* Response:
		{$response}
EOT;
		
		if (Config::get('development')) {
			$this->message = nl2br($content);
		} else {
			Mail::send(Config::get('developers'), 'Application error', $content, Mail::PRIORITY_HIGH);
		}
		
		include Layout::get();
	}
	
	protected function view()
	{
		if (Config::get('development')) {
			$message = $this->message;
		} else {
			$message = "The developer has been contacted to resolve the issue. Thank you.";
		}
		
		return <<<EOT
<h3>Oops, an error occured</h3>
<p class="error">
{$message}
</p>
EOT;
	}
}
