#TODO: categorize into multiple configuration files
root: domain.tld

development: true

# new way to choose stages
# do not use this!
stages:
  front: domain.tld
  back: domain.tld/admin

#TODO: better structure
templates:
  default: bootstrap
  options:
    bootstrap:
      css:
        - 'bootstrap'
        - 'humane-jackedup'
        - 'bootstrap-responsive'
      js:
        - 'jquery-1.7.2.min'
        - 'bootstrap/bootstrap-transition'
        - 'bootstrap/bootstrap-alert'
        - 'bootstrap/bootstrap-modal'
        - 'bootstrap/bootstrap-dropdown'
        - 'bootstrap/bootstrap-scrollspy'
        - 'bootstrap/bootstrap-tab'
        - 'bootstrap/bootstrap-tooltip'
        - 'bootstrap/bootstrap-popover'
        - 'bootstrap/bootstrap-button'
        - 'bootstrap/bootstrap-collapse'
        - 'bootstrap/bootstrap-carousel'
        - 'bootstrap/bootstrap-typeahead'
        - 'humane-3.0.0'
        - 'cognosys'
        - 'app'
    default:
      css:
      js:
    tablet:
      css:
      js:
    admin:
      css:
      js:

# database configurations
database:
  driver: pdo_mysql
  host: localhost
  port: 3306
  dbname: dbname
  user: root
  password: ""
  unix_socket: /var/run/mysqld/mysqld.sock
  charset: utf8
  #logging: false

# smtp configurations and default email settings
mail:
  subject: Subject Here
  from: from-address@domain.tld
  #reply: from-address@domain.tld
  smtp:
    server: smtp.domain.tld
    port: 25
    username: username
    password: password

# deprecated
debug:
  enabled: true
  report: all

# oversimplified routing, needs more features
routes:
  default: '/:controller/:action/:params'
  match:
    '/': 'home'
    '/login': 'user#login'
    '/logout': 'user#logout'

# TODO: not in use yet
# assets paths
assets: # for helpers
  js: /js
  css: /css
  img: /img
  less: /less
  coffee: /coffee

# LOW: not in use yet
# get request method with $_SERVER['REQUEST_METHOD']
# the user needs a key to authenticate
restful:
  enabled: false
  methods:
    get: show
    post: create
    put: update
    delete: delete

# this cogs are enabled
cogs:
 - Base
 - User
 - News
 - Samples

# to send emails with notifications
developers:
 - smartins.renato@gmail.com
